Introduce option to make lava renewable, off by default
minetest/minetest_game pull request #2773
Opened 2020-11-03 14:06 UTC by Oblomov

Considering MTG is being frozen feature-wise, I think it's important to clean up the remaining usability kinks.

Lava not being renewable is an important design decision that was taken 7 years ago
(introducing a significant, but justified change), and yet the question about making it renewable again
re-emerges periodically (the last hit I could find is from February this year, in the forum).

Making lava renewable again is something that users can do with a two-line mod, but I see having to go
through the (as limited as it might be) hassle of introducing a mod just to toggle this feature as a usability issue.

My proposal to fix this is to introduce a configuration option (that defaults to false, keeping the current behavior)
that can be toggled to make lava renewable again.
This eliminates the need to go through the mod system for something so trivial,
and is consistent with the spirit of making potentially destructive feature available,
albeit disabled by default.

2020-11-03 16:02 UTC, paramat commented on mods/default/nodes.lua
> +	-- If
Please remove the unnecessary comment.

2020-11-03 16:33 UTC, Oblomov commented on mods/default/nodes.lua
> +	-- If
Force-pushed with the comment removed.

2020-11-04 16:19 UTC, paramat commented
Requests for making lava (optionally) renewable seem rare, i cannot remember any GitHub issues requesting this before now.
It being renewable 7 years ago is such a long time ago as to be irrelevant to the large majority of users.
And MTG is feature-frozen.
So currently, i am not convinced a setting is justified, and disagree it is a usability issue.
This seems just one of many alterations some users would like, that should therefore be done by a mod (because we cannot add hundreds of new settings).

This PR is lacking the necessary explanation of the usefulness/need of renewable lava. Perhaps you could explain?
The fact MTG is feature-frozen means even more justification is needed, it needs to count as essential maintenance.

2020-11-04 21:50 UTC, Oblomov commented
There have been no issues opened, but the question comes up now and again in the forum, sometimes in top-level post, sometimes in discussions in other threads.

As for the usability vs mod issue, my argument is that this is a usability issue _precisely_ because as things stand the alternative is to require a mod for something that could be trivially be handled by a single setting, like using a cannon to kill a fly.

The counter-argument “we cannot add hundreds of new settings” is rather weak: while I can see why maintainers might be worried that this creates some kind of precedent, using this as an objection is a slippery slope fallacy: are there periodically requested toggles that are being asked for merging? not that I can see.

(And that's without even considering that I don't see anything particularly bad with having tuning knobs, especially for something like MTG that, as has been discussed in the feature-freeze proposal, lacks focus.)

2022-01-23 19:49 UTC, appgurueu requested changes

2022-01-23 19:49 UTC, appgurueu commented on mods/default/nodes.lua
> +	liquid_renewable = minetest.settings:get_bool("renewable_lava") or false,
I don't think the `or false` is needed.

2024-08-10 09:34 UTC, closed without merging

2024-08-10 09:34 UTC, SmallJoker commented
Please correct me if I'm wrong but there's yet no such request in the issue tracker, and no players bumping this PR, which makes me think that there's already a mod-based solution for overwriting lava, or there is simply no need for it.

For being marked as "Possible close" for almost four years, I'll be playing the bad cop and close it.