Stairs: fix rotation on place
minetest/minetest_game pull request #2814
Opened 2021-02-01 18:04 UTC by alek13

For example. slabs should placed vertically when places on a "wall".    
    
    use builtin \`rotate_node()\`:
    
    - so, use internal \`core.is_creative_enabled\`
    - fix rotation on stairs & slabs place
    - fix double \"take_item\" in creative mode

2021-02-01 18:44 UTC, MoNTE48 commented on mods/stairs/init.lua
> +			return minminetest.rotate_node(itemstack, placer, pointed_thing)
O_o

2021-02-01 21:14 UTC, alek13 commented on mods/stairs/init.lua
> +			return minminetest.rotate_node(itemstack, placer, pointed_thing)
oops :)  fixed

2021-02-01 21:46 UTC, sfan5 commented
PR must merge into `master`, not `stable-5`.

2021-02-01 22:04 UTC, alek13 commented
@sfan5 
If I understand correctly, `master` branch for now have changes for MT `5.4.0-dev` and possible uses new functionality, which it does not compatible with `5.3` (in general).

So if I want to fix this for `5.3` version, I need to PR into some corresponding branch (usually with same name - `5.3`).

Is there some way to fix this for `5.3` or I misunderstand the workflow ?

2021-02-01 22:11 UTC, sfan5 commented
Any new changes are put into `master`, then when 5.4.0 is released the current state of `master` is pushed into `stable-5`.
The only exception to this are backport releases, which we don't do currently (there will be no 5.3.1).

You cannot retroactively fix this in 5.3, but what you *can* do is to fix the bug for the next version.

2021-02-01 22:37 UTC, alek13 commented
@sfan5 
Sadly... :)
Maybe it would be better to create corresponding branches and when it have updates re-release MT with new MTG with patch up (`5.3.1`) ? Sounds crazy? :)
Or maybe some else solution ?

2021-02-01 22:49 UTC, alek13 commented
@sfan5 @rubenwardy 
Maybe best of all
 - create corresponding branches (`5.1`, `5.2`, `5.3`)
 - release MT without MTG and on first launch ask to download it
 - and than everyone can update MTG if there is updates for theirs version (in corresponding branch)
?

2021-02-01 23:46 UTC, alek13 commented
rebased on `master`

2021-02-01 23:54 UTC, alek13 commented
> @sfan5
> Sadly... :)
> Maybe it would be better to create corresponding branches and when it have updates re-release MT with new MTG with patch up (5.3.1) ? Sounds crazy? :)
> Or maybe some else solution ?

> @sfan5 @rubenwardy
> Maybe best of all
> - create corresponding branches (`5.1`, `5.2`, `5.3`)
> - release MT without MTG and on first launch ask to download it
> - and than everyone can update MTG if there is updates for theirs version (in corresponding branch)
> 
> ?

@sfan5 , @rubenwardy 
any thoughts ?
does it make sense to put it in a separate thread (issue) for discussion with others ?

2021-02-08 10:47 UTC, alek13 commented
@sfan5 can we merge this ?

2021-02-15 14:36 UTC, sfan5 commented
I haven't got around to reviewing and testing this PR yet, after I (or someone else) has this can be merged.

Regarding review: I'm wondering what happens to the special handling for `stairs:slab_`, does that just disappear?

2021-02-17 01:28 UTC, alek13 commented
not sure about what "special handling" you are meen, but all functionality works as before

2021-03-13 12:13 UTC, SmallJoker requested changes
![Side-place on stair](https://user-images.githubusercontent.com/1497498/111029582-b6192d80-83fd-11eb-9708-20db527ecee5.png)

This code is (at least partially) required to allow placing same stairs in a column (place to its side face). This PR breaks a very convenient way of building rooftops because the stairs are now tilted as shown above.

2023-12-24 12:46 UTC, sfan5 commented
Stale, closing.

2023-12-24 12:46 UTC, closed without merging