Removal of incorrect node (chests mod)
minetest/minetest_game pull request #2932
Opened 2022-02-22 05:03 UTC by baytuch

After the network failure, my chest stopped opening normally, but there is access to its inventory. Above the node of the chest was formed incorrect node. And the chest again begins to work normally.

def.drawtype == chest, - non airlike

2022-02-22 07:07 UTC, appgurueu requested changes

2022-02-22 07:07 UTC, appgurueu commented on mods/default/chests.lua
>  	-- allow ladders, signs, wallmounted things and torches to not obstruct
This comment has now moved to just above the wrong `if`.

2022-02-22 07:07 UTC, appgurueu commented on mods/default/chests.lua
> +		minetest.remove_node(above)
You seem to be deleting arbitrary mesh nodes here. This should be more specific; in it's current form it's prone to abuse and mod breakage both within MTG and outside of MTG (concerning 3rd-party mods).

2023-12-24 12:44 UTC, sfan5 commented
Stale, closing.

2023-12-24 12:44 UTC, closed without merging