Fix furnace fire sound stopping too slowly
minetest/minetest_game pull request #2955
Opened 2022-05-24 15:28 UTC by Wuzzy2

Partial fix of #2836 (this is a monster issue with multiple issues in one). This will be fixed:

> The furnace sound doesn't stop once the fire stops, but continues for a few seconds

This PR does the following:

When the furnace fire goes out, or when the `default:furnace_active` node destructs, the fire sound fade out. Because fire sounds can overlap (the sound effect is 10 seconds long, and is repeated every 5 seconds), the table that holds the sound handles needs to hold multiple sound handles for the same node at once (up to 3). When the sound needs to be stopped, `minetest.sound_fade` is called for every remembered sound handle of that node, then sets the table entry to `nil`.
I chose `sound_fade` rather than `sound_stop` because it sounds nicer.

How to test:

Test 1: Place a furnace. Activate it. Dig it while the fire is still burning.
Test 2: Place a furnace. Activate it and let the flame go out.

Expected: The fire sound should quickly fade out.
Previous buggy behavior: The fire sound continues to play for about 5 to 10 seconds.

2022-05-24 15:41 UTC, appgurueu approved these changes
Some minor code style improvements are possible IMO. Fine (especially by MTG's standards) either way.

2022-05-24 15:43 UTC, appgurueu requested changes
Retracting approval as I feel this might leak memory: What if furnaces are unloaded (i.e. neither `on_destruct` nor the timer are called)? I believe this probably needs some `minetest.after`s to ensure sounds are removed from the table if they have expired.

2022-05-24 18:44 UTC, sfan5 commented on mods/default/furnace.lua
> +			minetest.sound_fade(sound_ids, -1, 0)
typo

2022-05-25 08:53 UTC, Wuzzy2 commented
Okay, I added a simple `minetest.after` to clean up sound IDs and also the whole table, if needed.

2022-05-25 09:12 UTC, appgurueu commented on mods/default/furnace.lua
> +			end, {sound_id=sound_id, hash=hash})
passing `t` is not needed, just use the upvalues

2022-05-25 16:38 UTC, SmallJoker commented
Shouldn't this be an engine feature to automatically fade out or remove node-specific sounds once the node is removed? This way you'll always need to keep track of sounds in mods which seems to be an unnecessary task.

2022-05-26 07:21 UTC, Wuzzy2 commented
YES! Obviously.
But this is kinda sorta unrelated, as long the engine doesn't support it, this PR stands.

2022-05-29 13:03 UTC, Wuzzy2 commented
@appgurueu: Done!

2022-05-29 13:19 UTC, appgurueu approved these changes
Works, code looks fine now.

2022-05-29 19:15 UTC, sfan5 approved these changes
Didn't test, trusting @appgurueu on that

2022-05-29 19:16 UTC, merged